# Employee Attrition KPI Analysis

This notebook calculates key performance indicators (KPIs) from the cleaned IBM HR Employee Attrition dataset. These KPIs summarize workforce characteristics, employee attrition patterns, satisfaction metrics, and experience-related insights. The calculated KPIs will be used to support business insights and the Tableau dashboard.

## Importing Required Libraries

In [2]:
# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully.")

Libraries imported successfully.

## Loading the Cleaned Dataset

In [5]:
df = pd.read_csv(r"C:\Users\Geeth\OneDrive\Documents\data analytics project\EMPLOYEE-ATTRITION-ANALYSIS-PROJECT\Data\Cleaned\IBM_HR_Employee_Attrition_Cleaned.csv")
print("Dataset loaded successfully.")
df.head()

Dataset loaded successfully.

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

# 1. Workforce KPIs

## KPI 1: Total Employees

In [6]:
total_employees = len(df)
print("Total Employees:", total_employees)

Total Employees: 1470

## KPI 2: Employees Left

In [7]:
employees_left = len(df[df["Attrition"] == "Yes"])
print("Employees Left:", employees_left)

Employees Left: 237

## KPI 3: Employees Stayed

In [8]:
employees_stayed = len(df[df["Attrition"] == "No"])
print("Employees Stayed:", employees_stayed)

Employees Stayed: 1233

## KPI 4: Overall Attrition Rate

In [13]:
attrition_rate = (employees_left / total_employees) * 100
print("Overall Attrition Rate:",round( attrition_rate,2), "%")

Overall Attrition Rate: 16.12 %

## KPI 5: Average Employee Age

In [14]:
average_age = df["Age"].mean()
print("Average Employee Age:", round(average_age, 2), "years")

Average Employee Age: 36.92 years

## KPI 6: Average Monthly Income

In [15]:
average_income = df["MonthlyIncome"].mean()
print("Average Monthly Income:", round(average_income, 2))

Average Monthly Income: 6502.93

## KPI 7: Average Total Working Years

In [16]:
average_working_years = df["TotalWorkingYears"].mean()
print("Average Total Working Years:", round(average_working_years, 2), "years")

Average Total Working Years: 11.28 years

# 2. Department KPIs

## KPI 8: Department-wise Attrition

In [17]:
department_attrition = df[df["Attrition"] == "Yes"].groupby("Department").size()
print(department_attrition)

Department
Human Resources            12
Research & Development    133
Sales                      92
dtype: int64

## Department-wise Attrition Rate

In [29]:
department = df.groupby(["Department","Attrition"]).size().unstack()
department["Total Employees"] = department["Yes"] + department["No"]

department["Attrition Rate (%)"] = (department["Yes"] / department["Total Employees"]) * 100
department["Attrition Rate (%)"] = department["Attrition Rate (%)"].round(2)

department = department.sort_values(by="Attrition Rate (%)", ascending=False)
department

Attrition                No  Yes  Total Employees  Attrition Rate (%)
Department
Sales                   354   92              446               20.63
Human Resources          51   12               63               19.05
Research & Development  828  133              961               13.84

# 3. Job Role KPIs

## KPI 9: Job Role-wise Attrition

In [19]:
jobrole_attrition = df[df["Attrition"] == "Yes"].groupby("JobRole").size()
print(jobrole_attrition)

JobRole
Healthcare Representative     9
Human Resources              12
Laboratory Technician        62
Manager                       5
Manufacturing Director       10
Research Director             2
Research Scientist           47
Sales Executive              57
Sales Representative         33
dtype: int64

## Job Role-wise Attrition Rate

In [30]:
jobrole = df.groupby(["JobRole","Attrition"]).size().unstack()
jobrole["Total Employees"] = jobrole["Yes"] + jobrole["No"]

jobrole["Attrition Rate (%)"] = (jobrole["Yes"] / jobrole["Total Employees"]) * 100
jobrole["Attrition Rate (%)"] = jobrole["Attrition Rate (%)"].round(2)

jobrole = jobrole.sort_values(by="Attrition Rate (%)", ascending=False)
jobrole

Attrition                   No  Yes  Total Employees  Attrition Rate (%)
JobRole
Sales Representative        50   33               83               39.76
Laboratory Technician      197   62              259               23.94
Human Resources             40   12               52               23.08
Sales Executive            269   57              326               17.48
Research Scientist         245   47              292               16.10
Manufacturing Director     135   10              145                6.90
Healthcare Representative  122    9              131                6.87
Manager                     97    5              102                4.90
Research Director           78    2               80                2.50

# 4. Demographic KPIs

## KPI 10 : Gender-wise Attrition

In [20]:
gender_attrition = df[df["Attrition"] == "Yes"].groupby("Gender").size()
print(gender_attrition)

Gender
Female     87
Male      150
dtype: int64

## KPI 11 : Marital Status-wise Attrition

In [21]:
marital_attrition = df[df["Attrition"] == "Yes"].groupby("MaritalStatus").size()
print(marital_attrition)

MaritalStatus
Divorced     33
Married      84
Single      120
dtype: int64

# 5. Work Pattern KPIs

## KPI 12 : Overtime-wise Attrition

In [22]:
overtime_attrition = df[df["Attrition"] == "Yes"].groupby("OverTime").size()
print(overtime_attrition)

OverTime
No     110
Yes    127
dtype: int64

## Overtime Attrition Rate

In [31]:
overtime = df.groupby(["OverTime","Attrition"]).size().unstack()
overtime["Total Employees"] = overtime["Yes"] + overtime["No"]

overtime["Attrition Rate (%)"] = (overtime["Yes"] / overtime["Total Employees"]) * 100
overtime["Attrition Rate (%)"] = overtime["Attrition Rate (%)"].round(2)

overtime = overtime.sort_values(by="Attrition Rate (%)", ascending=False)
overtime

Attrition   No  Yes  Total Employees  Attrition Rate (%)
OverTime
Yes        289  127              416               30.53
No         944  110             1054               10.44

## KPI 13 : Business Travel-wise Attrition

In [23]:
businesstravel_attrition = df[df["Attrition"] == "Yes"].groupby("BusinessTravel").size()
print(businesstravel_attrition)

BusinessTravel
Non-Travel            12
Travel_Frequently     69
Travel_Rarely        156
dtype: int64

## Business Travel Attrition Rate

In [32]:
travel = df.groupby(["BusinessTravel","Attrition"]).size().unstack()
travel["Total Employees"] = travel["Yes"] + travel["No"]

travel["Attrition Rate (%)"] = (travel["Yes"] / travel["Total Employees"]) * 100
travel["Attrition Rate (%)"] = travel["Attrition Rate (%)"].round(2)

travel = travel.sort_values(by="Attrition Rate (%)", ascending=False)
travel

Attrition           No  Yes  Total Employees  Attrition Rate (%)
BusinessTravel
Travel_Frequently  208   69              277               24.91
Travel_Rarely      887  156             1043               14.96
Non-Travel         138   12              150                8.00

# 6. Satisfaction KPIs

## KPI 14 : Job Satisfaction-wise Attrition

In [24]:
jobsatisfaction_attrition = df[df["Attrition"] == "Yes"].groupby("JobSatisfaction").size()
print(jobsatisfaction_attrition)

JobSatisfaction
1    66
2    46
3    73
4    52
dtype: int64

## Job Satisfaction Attrition Rate

In [33]:
jobsatisfaction = df.groupby(["JobSatisfaction","Attrition"]).size().unstack()
jobsatisfaction["Total Employees"] = jobsatisfaction["Yes"] + jobsatisfaction["No"]

jobsatisfaction["Attrition Rate (%)"] = (jobsatisfaction["Yes"] / jobsatisfaction["Total Employees"]) * 100
jobsatisfaction["Attrition Rate (%)"] = jobsatisfaction["Attrition Rate (%)"].round(2)

jobsatisfaction = jobsatisfaction.sort_values(by="Attrition Rate (%)", ascending=False)
jobsatisfaction

Attrition         No  Yes  Total Employees  Attrition Rate (%)
JobSatisfaction
1                223   66              289               22.84
3                369   73              442               16.52
2                234   46              280               16.43
4                407   52              459               11.33

## KPI 15 : Environment Satisfaction-wise Attrition

In [25]:
environment_attrition = df[df["Attrition"] == "Yes"].groupby("EnvironmentSatisfaction").size()
print(environment_attrition)

EnvironmentSatisfaction
1    72
2    43
3    62
4    60
dtype: int64

## Environment Satisfaction Attrition Rate

In [34]:
environmentsatisfaction = df.groupby(["EnvironmentSatisfaction","Attrition"]).size().unstack()
environmentsatisfaction["Total Employees"] = environmentsatisfaction["Yes"] + environmentsatisfaction["No"]

environmentsatisfaction["Attrition Rate (%)"] = (environmentsatisfaction["Yes"] / environmentsatisfaction["Total Employees"]) * 100
environmentsatisfaction["Attrition Rate (%)"] = environmentsatisfaction["Attrition Rate (%)"].round(2)

environmentsatisfaction = environmentsatisfaction.sort_values(by="Attrition Rate (%)", ascending=False)
environmentsatisfaction

Attrition                 No  Yes  Total Employees  Attrition Rate (%)
EnvironmentSatisfaction
1                        212   72              284               25.35
2                        244   43              287               14.98
3                        391   62              453               13.69
4                        386   60              446               13.45

##  KPI 16 : Work-Life Balance-wise Attrition

In [26]:
worklife_attrition = df[df["Attrition"] == "Yes"].groupby("WorkLifeBalance").size()
print(worklife_attrition)

WorkLifeBalance
1     25
2     58
3    127
4     27
dtype: int64

## Work-Life Balance Attrition Rate

In [35]:
worklifebalance = df.groupby(["WorkLifeBalance","Attrition"]).size().unstack()
worklifebalance["Total Employees"] = worklifebalance["Yes"] + worklifebalance["No"]

worklifebalance["Attrition Rate (%)"] = (worklifebalance["Yes"] / worklifebalance["Total Employees"]) * 100
worklifebalance["Attrition Rate (%)"] = worklifebalance["Attrition Rate (%)"].round(2)

worklifebalance = worklifebalance.sort_values(by="Attrition Rate (%)", ascending=False)
worklifebalance

Attrition         No  Yes  Total Employees  Attrition Rate (%)
WorkLifeBalance
1                 55   25               80               31.25
4                126   27              153               17.65
2                286   58              344               16.86
3                766  127              893               14.22

# 7. Experience KPIs

##  KPI 17 : Job Level-wise Attrition

In [27]:
joblevel_attrition = df[df["Attrition"] == "Yes"].groupby("JobLevel").size()
print(joblevel_attrition)

JobLevel
1    143
2     52
3     32
4      5
5      5
dtype: int64

##  KPI 18 : Total Working Years-wise Attrition

In [28]:
experience_attrition = df[df["Attrition"] == "Yes"].groupby("TotalWorkingYears").size()
print(experience_attrition)

TotalWorkingYears
0      5
1     40
2      9
3      9
4     12
5     16
6     22
7     18
8     16
9     10
10    25
11     7
12     5
13     3
14     4
15     5
16     3
17     3
18     4
19     3
20     2
21     1
22     2
23     2
24     3
25     1
26     1
28     1
31     1
33     1
34     1
40     2
dtype: int64